# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.cache/wt [current_project]
set_property parent.project_path C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/Ship.coe
add_files C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/bullet.coe
add_files C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/Alien.coe
add_files c:/Users/larsl/Documents/E-ICT/digitale2/spehz_invadorz/spehz_invadorz.srcs/sources_1/ip/bullet.coe
add_files c:/Users/larsl/Documents/E-ICT/digitale2/spehz_invadorz/spehz_invadorz.srcs/sources_1/ip/Ship.coe
add_files c:/Users/larsl/Documents/E-ICT/digitale2/spehz_invadorz/spehz_invadorz.srcs/sources_1/ip/Alien.coe
add_files -quiet c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
add_files -quiet c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp]
add_files -quiet c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp
set_property used_in_implementation false [get_files c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp]
add_files -quiet c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/new/vga_640x480.vhd
  C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/new/top.vhd
  C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/new/vga_beeld.vhd
  C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/new/DebouncerForControls.vhd
  C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/new/gameTicksClockDiv.vhd
  C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/sources_1/new/LEDaansturing.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/constrs_1/imports/Digitale Elektronica/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/larsl/Documents/E-ICT/digitale2/space_invaders_V4/space_invaders_V4.srcs/constrs_1/imports/Digitale Elektronica/Basys3_Master.xdc}}]


synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
